package com.ssverma.core.ui.theme

import androidx.compose.ui.graphics.Color

val filesLightPrimary = Color(0xFF005AC1)
val filesLightOnPrimary = Color(0xFFFFFFFF)
val filesLightPrimaryContainer = Color(0xFFD8E2FF)
val filesLightOnPrimaryContainer = Color(0xFF001A41)
val filesLightSecondary = Color(0xFF575E71)
val filesLightOnSecondary = Color(0xFFFFFFFF)
val filesLightSecondaryContainer = Color(0xFFDBE2F9)
val filesLightOnSecondaryContainer = Color(0xFF141B2C)
val filesLightTertiary = Color(0xFF715573)
val filesLightOnTertiary = Color(0xFFFFFFFF)
val filesLightTertiaryContainer = Color(0xFFFBD7FC)
val filesLightOnTertiaryContainer = Color(0xFF29132D)
val filesLightError = Color(0xFFBA1A1A)
val filesLightErrorContainer = Color(0xFFFFDAD6)
val filesLightOnError = Color(0xFFFFFFFF)
val filesLightOnErrorContainer = Color(0xFF410002)
val filesLightBackground = Color(0xFFFEFBFF)
val filesLightOnBackground = Color(0xFF1B1B1F)
val filesLightSurface = Color(0xFFFEFBFF)
val filesLightOnSurface = Color(0xFF1B1B1F)
val filesLightSurfaceVariant = Color(0xFFE1E2EC)
val filesLightOnSurfaceVariant = Color(0xFF44474F)
val filesLightOutline = Color(0xFF74777F)
val filesLightInverseOnSurface = Color(0xFFF2F0F4)
val filesLightInverseSurface = Color(0xFF303033)
val filesLightInversePrimary = Color(0xFFADC6FF)
val filesLightShadow = Color(0xFF000000)
val filesLightSurfaceTint = Color(0xFF005AC1)
val filesLightOutlineVariant = Color(0xFFC4C6D0)
val filesLightScrim = Color(0xFF000000)

val filesDarkPrimary = Color(0xFFADC6FF)
val filesDarkOnPrimary = Color(0xFF002E69)
val filesDarkPrimaryContainer = Color(0xFF004494)
val filesDarkOnPrimaryContainer = Color(0xFFD8E2FF)
val filesDarkSecondary = Color(0xFFBFC6DC)
val filesDarkOnSecondary = Color(0xFF293041)
val filesDarkSecondaryContainer = Color(0xFF3F4759)
val filesDarkOnSecondaryContainer = Color(0xFFDBE2F9)
val filesDarkTertiary = Color(0xFFDEBCDF)
val filesDarkOnTertiary = Color(0xFF402843)
val filesDarkTertiaryContainer = Color(0xFF583E5B)
val filesDarkOnTertiaryContainer = Color(0xFFFBD7FC)
val filesDarkError = Color(0xFFFFB4AB)
val filesDarkErrorContainer = Color(0xFF93000A)
val filesDarkOnError = Color(0xFF690005)
val filesDarkOnErrorContainer = Color(0xFFFFDAD6)
val filesDarkBackground = Color(0xFF1B1B1F)
val filesDarkOnBackground = Color(0xFFE3E2E6)
val filesDarkSurface = Color(0xFF1B1B1F)
val filesDarkOnSurface = Color(0xFFE3E2E6)
val filesDarkSurfaceVariant = Color(0xFF44474F)
val filesDarkOnSurfaceVariant = Color(0xFFC4C6D0)
val filesDarkOutline = Color(0xFF8E9099)
val filesDarkInverseOnSurface = Color(0xFF1B1B1F)
val filesDarkInverseSurface = Color(0xFFE3E2E6)
val filesDarkInversePrimary = Color(0xFF005AC1)
val filesDarkShadow = Color(0xFF000000)
val filesDarkSurfaceTint = Color(0xFFADC6FF)
val filesDarkOutlineVariant = Color(0xFF44474F)
val filesDarkScrim = Color(0xFF000000)


val seed = Color(0xFF4285F4)
